package game

import "time"

// DungeonState represents the current state of a dungeon instance.
type DungeonState int

const (
	// DungeonStateActive means the dungeon is in play.
	DungeonStateActive DungeonState = iota
	// DungeonStateCleared means all bosses have been defeated.
	DungeonStateCleared
	// DungeonStateFailed means the party was wiped.
	DungeonStateFailed
)

// DungeonRoomType categorises rooms for encounter seeding and narrative framing.
type DungeonRoomType string

const (
	DungeonRoomTypeEntrance DungeonRoomType = "entrance"
	DungeonRoomTypeChamber  DungeonRoomType = "chamber"
	DungeonRoomTypeBoss     DungeonRoomType = "boss"
	DungeonRoomTypeTreasure DungeonRoomType = "treasure"
	DungeonRoomTypeCorridor DungeonRoomType = "corridor"
	DungeonRoomTypeJunction DungeonRoomType = "junction"
)

// DungeonRoomData is the persistent representation of one room.
// It stores both narrative content and spatial connections.
type DungeonRoomData struct {
	// ID is the room's unique identifier (from environments.ZoneData.ID).
	ID string `json:"id" dynamodbav:"id"`

	// Name is the room's display name (generated by Claude framing call).
	Name string `json:"name" dynamodbav:"name"`

	// Description is the room's narrative description (generated by Claude).
	Description string `json:"description,omitempty" dynamodbav:"description,omitempty"`

	// Type classifies the room for encounter/loot seeding.
	Type DungeonRoomType `json:"type" dynamodbav:"type"`

	// ConnectedRoomIDs lists rooms reachable from this one (undirected graph edges).
	ConnectedRoomIDs []string `json:"connected_room_ids,omitempty" dynamodbav:"connected_room_ids,omitempty"`

	// Connections is the directional map used by the runtime (direction → roomID).
	// Derived from ConnectedRoomIDs during world-gen via BFS spatial layout.
	Connections map[string]string `json:"connections,omitempty" dynamodbav:"connections,omitempty"`

	// Coordinates are the 2D map coordinates assigned during world-gen.
	// X increases east, Y increases south, Z is floor level.
	Coordinates Coordinates `json:"coordinates" dynamodbav:"coordinates"`
}

// DungeonData is the persistent dungeon layout produced by world-gen.
// It replaces the old map[string]Area + seedMonsters approach and is stored
// in SaveState as of SchemaVersion 4.
type DungeonData struct {
	// ID is the dungeon's unique identifier.
	ID string `json:"id" dynamodbav:"id"`

	// StartRoomID is the entrance room — where players begin.
	StartRoomID string `json:"start_room_id" dynamodbav:"start_room_id"`

	// BossRoomID is the final encounter room.
	BossRoomID string `json:"boss_room_id" dynamodbav:"boss_room_id"`

	// CurrentRoomID tracks all-party current room (single-party convenience field).
	// In multi-player, individual player positions live in Players[uid].LocationID.
	CurrentRoomID string `json:"current_room_id" dynamodbav:"current_room_id"`

	// Rooms is the full room map keyed by room ID.
	Rooms map[string]*DungeonRoomData `json:"rooms" dynamodbav:"rooms"`

	// RevealedRooms tracks which rooms players have visited (for fog-of-war).
	RevealedRooms map[string]bool `json:"revealed_rooms,omitempty" dynamodbav:"revealed_rooms,omitempty"`

	// Seed is the RNG seed used for deterministic generation.
	Seed int64 `json:"seed" dynamodbav:"seed"`

	// State is the dungeon lifecycle stage.
	State DungeonState `json:"state" dynamodbav:"state"`

	// CreatedAt is when world-gen completed.
	CreatedAt time.Time `json:"created_at" dynamodbav:"created_at"`
}
